### PR TITLE
Support AnkiMobile user actions

### PR DESCRIPTION
**Pull request by abdnh**
See AnKing-Memberships/AnKing-Note-Types#110 and AnKing-Memberships/AnKing-Note-Types#113

Currently the same actions are defined for all notetypes for simplicity, so it's possible to assign actions that don't do anything in a given notetype.
image

## TODO

- [ ] Maybe prevent invalid actions from being assigned at all. Looks like this require more extensive code changes and it may not be worth it.
- [x] We probably shouldn't show an error if the user has custom functions assigned to the actions.

### CODE REVIEW

**Comment by AnKingMed** [comment]
I don't think we actually need to update the note types here because there is a github action that does that and pulls things over from the other repo (just FYI for the future)

**Comment by AnKingMed** [comment]
@abdnh I just got this error when testing:

> When loading '⁨AnKing Notetypes⁩':
⁨Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "/Users/Nick/Library/Application Support/Anki2/addons21/anking_notetypes/__init__.py", line 9, in <module>
    from .gui.config_window import NotetypesConfigWindow
  File "/Users/Nick/Library/Application Support/Anki2/addons21/anking_notetypes/gui/config_window.py", line 14, in <module>
    from ..notetype_setting import NotetypeSetting, NotetypeSettingException
  File "/Users/Nick/Library/Application Support/Anki2/addons21/anking_notetypes/notetype_setting.py", line 7, in <module>
    from .notetype_setting_definitions import anking_notetype_names
  File "/Users/Nick/Library/Application Support/Anki2/addons21/anking_notetypes/notetype_setting_definitions.py", line 687, in <module>
    setting_configs = OrderedDict(**setting_configs, **all_btns_setting_configs())
  File "/Users/Nick/Library/Application Support/Anki2/addons21/anking_notetypes/notetype_setting_definitions.py", line 592, in all_btns_setting_configs
    for notetype_name in anking_notetype_templates().keys():
  File "/Users/Nick/Library/Application Support/Anki2/addons21/anking_notetypes/notetype_setting_definitions.py", line 570, in anking_notetype_templates
    back_template = (x / ("Back Template.html")).read_text(
  File "pathlib", line 1266, in read_text
  File "pathlib", line 1252, in open
  File "pathlib", line 1120, in _opener
FileNotFoundError: [Errno 2] No such file or directory: '/Users/Nick/Library/Application Support/Anki2/addons21/anking_notetypes/note_types/Physeo-Cloze/Back Template.html'

**Comment by AnKingMed** [comment]
It looks like in the note types repo, the latest npm build that automatically ran after I merged the PR deleted the back template. Can you look into why that is?

[npm build](https://github.com/AnKing-Memberships/AnKing-Note-Types/commit/b3123a578bdbde1596d8122c715018cf86e088cc)

**Comment by abdnh** [comment]
Yes, I also ran into this issue. That's why I closed AnKing-Memberships/AnKing-Note-Types#113
Will look into that.

**Comment by AnKingMed** [comment]
Thanks. I'll wait to test things till we figure that out. I've never had that happen before. Do you think it could be due to you adding content to the back.ejs file?

**Comment by AnKingMed** [comment]
@RisingOrange made the npm build so maybe he could look quickly if he has a second

**Comment by abdnh** [comment]
The templates are removed by the build script before being regenerated. The logs show this error:
```
Could not find the include file "src/components/ankiMobileUserActions.ejs"
```

Which is strange. I have no idea why it fails to find the ankiMobileUserActions.ejs file. I don't have issue running `npm run build` locally.

**Comment by AnKingMed** [comment]
looks like the M in mobile isn't capitalized. Maybe that's why?

**Comment by abdnh** [comment]
Yes, just found about this.

**Comment by abdnh** [comment]
I ran the script to update the notetypes here. Problem solved.

**Comment by AnKingMed** [comment]
Awesome. Thanks!

**Pull request merged**
