### PR TITLE
Add editor menu item to blur/unblur images

### PR DESCRIPTION
**Pull request by abdnh**
This adds an option under the editor's dropdown menu to blur/unblur images. See https://github.com/AnKing-VIP/AnKing-Note-Types/issues/148 and https://github.com/AnKing-VIP/anki-wrapper/pull/11 for context.

image

@AnKingMed

### CODE REVIEW

**Comment by AnKingMed** [comment]
So this just adds the menu class "blur" and then we control that from the css correct?

**Comment by abdnh** [comment]
Yes.

**Comment by AnKingMed** [comment]
This is only working for me on some images and I haven't found a pattern to it. Doesn't seem to work on most of the AnKing Note Types but then it works on some.. not sure why. https://recording.theanking.com/zP3dJJkW

**Comment by abdnh** [comment]
I think I know what's causing this. I tried to limit showing the option to the AnKing note types using their standard names, but this doesn't work for AnkiHub note types for example. I'll revert this change. Do you think it's good idea to rename the option to "AnKing Notetypes: Blur/Unblur Image" to make it more clear where the option comes from and where it works by default?

**Comment by AnKingMed** [comment]
Yeah that's a good idea!

**Comment by shmuelsash** [comment]
For nid:1689605558239 this menu option does not work to blur the image
I had to add the class manually

Here's the html
`<div><a style="font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, &quot;" title="de:User:Ernesto Che Guevara, Public domain, via Wikimedia Commons" href="https://commons.wikimedia.org/wiki/File:Hirsuties_papillaris_coronae_glandis.jpg">Hirsuties papillaris coronae glandis</a><br><br><span style="font-size: 10pt;"><i>Photo credit: <a href="https://commons.wikimedia.org/wiki/File:Hirsuties_papillaris_coronae_glandis.jpg">Ernesto Che Guevara</a>, Public domain, via Wikimedia Commons</i></span></div>`

**Comment by abdnh** [comment]
@shmuelsash I overlooked external images - Will try to fix this.

**Pull request merged**
